### ISSUE TITLE
REQUEST: deploy chatgpt plugin for pingcap/tiflow

### ISSUE THREAD

**Issue by wuhuizuo** [ti-community-infra/configs#1050]
### GitHub Repo Name

pingcap/tiflow

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.net/).

- chatgpt (external plugin)

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function
