### ISSUE TITLE
REQUEST: deploy prow for @pingcap/tidb

### ISSUE THREAD

**Issue by hi-rustin** [ti-community-infra/configs#147]
### GitHub Repo Name
@pingcap/tidb

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.io/).

All plugins.

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration(#148)
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots(@sykp241095 )
- [ ] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by hi-rustin** [comment]
@sykp241095 Can you grant the tidb admin permissions to ti-chi-bot？

**Comment by sykp241095** [comment]
> ti-chi-bot

Done
