### ISSUE TITLE
REQUEST: deploy prow for Docs SIG

### ISSUE THREAD

**Issue by ran-huang** [ti-community-infra/configs#151]
### GitHub Repo Name
@pingcap/docs, @pingcap/docs-cn, @pingcap/docs-tidb-operator, @pingcap/docs-dm

### Which plugins do you want to deploy
We want to deploy all plugins **except ti-community-blunderbuss.** (please don't auto-assign reviewers)

We also want to customize a plugin:
- `require-matching-label`: require a `translation/xxx` label for each PR.

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [ ] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by hi-rustin** [comment]
I'll be working on this next week.

**Comment by ran-huang** [comment]
@hi-rustin Any update on this?

**Comment by hi-rustin** [comment]
> @hi-rustin Any update on this?

I'm really sorry, I was really busy last week, I will help you deploy it by tomorrow at the latest.

**Comment by hi-rustin** [comment]
@Mini256 will help you deploy it.
