### ISSUE TITLE
REQUEST: deploy prow for Migration SIG

### ISSUE THREAD

**Issue by overvenus** [ti-community-infra/configs#173]
### GitHub Repo Name

- [x] @pingcap/dm(https://github.com/ti-community-infra/configs/pull/204) 
- [x] @pingcap/dumpling(https://github.com/ti-community-infra/configs/pull/201) 
- [x] @pingcap/br (https://github.com/ti-community-infra/configs/pull/208)
- [x] @pingcap/ticdc(https://github.com/ti-community-infra/configs/pull/207)
- [x] @pingcap/tidb-tools(https://github.com/ti-community-infra/configs/pull/205)

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.io/).

All plugins.

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by hi-rustin** [comment]
We will deploy it in the next week.

/assign @Mini256 @hi-rustin
