### ISSUE TITLE
REQUEST: deploy cherrypicker for pd

### ISSUE THREAD

**Issue by hi-rustin** [ti-community-infra/configs#275]
### GitHub Repo Name
tikv/pd

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.io/).

e.g. 
- cherrypicker

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] Modify the label configuration
- [x] Add cherrypicker plugin
~~Add the milestone configuration~~
