### ISSUE TITLE
REQUEST: deploy cherrypicker for SIG Migration

### ISSUE THREAD

**Issue by kennytm** [ti-community-infra/configs#278]
### GitHub Repo Name

- [ ] pingcap/br
- [x] pingcap/dm
- [x] pingcap/dumpling
- [x] pingcap/ticdc

### Which plugins do you want to deploy

- cherrypicker

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by kennytm** [comment]
Do we also need separate issues for `pingcap/dumpling`, `pingcap/ticdc` and `pingcap/dm`? 😅

**Comment by hi-rustin** [comment]
> Do we also need separate issues for `pingcap/dumpling`, `pingcap/ticdc` and `pingcap/dm`? 😅

Maybe it would be better to change the title to `for SIG migration`?

**Comment by kennytm** [comment]
Done.

**Comment by hi-rustin** [comment]
/hold

- [ ] Waiting for @lance6716 approve

- [ ] Waiting for @lance6716 modify labels

- [ ] Waiting for stop sre-bot service
