### ISSUE TITLE
REQUEST: deploy cherrypicker for docs-cn, docs, docs-dm, docs-tidb-operator

### ISSUE THREAD

**Issue by qiancai** [ti-community-infra/configs#279]
### GitHub Repo Name
- pingcap/docs-cn
- pingcap/docs
- pingcap/docs-dm
- pingcap/docs-tidb-operator

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.io/).

- cherrypicker

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] Add cherrypicker plugin
