### ISSUE TITLE
REQUEST: deploy prow for chaos-mesh/website-zh and chaos-mesh/website

### ISSUE THREAD

**Issue by qiancai** [ti-community-infra/configs#289]
### GitHub Repo Name
https://github.com/chaos-mesh/website-zh
https://github.com/chaos-mesh/website

### Which plugins do you want to deploy
Same plugins as that configured for pingcap/docs-cn/ and pingcap/docs

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function
