### ISSUE TITLE
REQUEST: deploy prow for tidb-binlog

### ISSUE THREAD

**Issue by lichunzhu** [ti-community-infra/configs#346]
### GitHub Repo Name
pingcap/tidb-binlog

### Which plugins do you want to deploy
- hold
- wip
- tide
- lifecycle
- cherrypicker

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [ ] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [ ] @ti-community-infra/sig-community-infra  Turn off the old robot function

**Comment by Mini256** [comment]
@lichunzhu I will help you deploy it tomorrow or the day after tomorrow.
