### ISSUE TITLE
REQUEST: deploy prow for pingcap/dev-guide

### ISSUE THREAD

**Issue by TomShawn** [ti-community-infra/configs#443]
### GitHub Repo Name

[pingcap/dev-guide](https://github.com/pingcap/dev-guide)

### Which plugins do you want to deploy

We want to deploy all plugins **except ti-community-blunderbuss.** (please don't auto-assign reviewers)

We also want to customize a plugin:

* `require-matching-label`: require a `translation/xxx` label for each PR.

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Add the requested plugin configuration
- [x] @ti-community-infra/sig-community-infra  Add repository admin to Robots
- [x] @ti-community-infra/sig-community-infra  Turn off the old robot function
