### ISSUE TITLE
Deploy Request: enable prow for tikv

### ISSUE THREAD

**Issue by hi-rustin** [ti-community-infra/configs#63]
## Deploy Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Is your feature request related to a Issue or PR(Optional)

- Which project: https://github.com/tikv/tikv

### Describe the deploy you'd like:

We want to enable prow for tikv.

### TODO

- [x] @hi-rustin bump the prow and plugins version (testing all plugins) (https://github.com/ti-community-infra/configs/pull/69)
- [x] @hi-rustin update `rerere` component docs
- [x] @zhouqiang-cl help us organize the CI tasks that each branch of tikv requires to be passed
- [x] @hi-rustin add `rerere` jobs for tikv all branchs
- [x] @hi-rustin configure the plugins for tikv
- [x] @sykp241095 give @ti-community-prow-bot tikv admin permission.
- [x] @AndreMouche  @hi-rustin communicate with tikv team, get approval and deploy it
- [x] @AndreMouche turn off the ti-srebot merge feature

**Comment by hi-rustin** [comment]
We need to bump prow version form `v20201204-d90be1ef6b` to `v20201217-2de500de27`.

We need to testing the features:

- [ ] [label plugin changes](https://github.com/ti-community-infra/ti-community-prow/pull/190)
- [ ] [external configs ptah](https://github.com/ti-community-infra/ti-community-prow/pull/202)
- [ ] [owners plugin changes](https://github.com/ti-community-infra/ti-community-prow/pull/210)
- [ ] [auto responder plugin changes](https://github.com/ti-community-infra/ti-community-prow/pull/218)

**Comment by hi-rustin** [comment]
/close

By https://github.com/ti-community-infra/configs/pull/84
