### ISSUE TITLE
REQUEST: add prow OWNERS file to these repos and make prow config changes

### ISSUE THREAD

**Issue by wuhuizuo** [ti-community-infra/configs#824]
### GitHub Repo Names

- ti-community-infra/test-prod
- ti-community-infra/tichi
- ti-community-infra/ti-community-bot
- ti-community-infra/rfcs
- ti-community-infra/devstats
- ti-community-infra/devstats-dev-guide
- tikv/pd
- tikv/tikv
- tikv/raft-engine
- tikv/client-go
- tikv/community
- pingcap/tidb-dashboard
- pingcap/tidb-operator
- pingcap/tiup
- pingcap/community
- pingcap/tidb
- pingcap/docs
- pingcap/docs-cn
- ~pingcap/docs-dm~
- pingcap/docs-tidb-operator
- pingcap/tidb-tools
- pingcap/tiflow
- pingcap/tidb-binlog
- pingcap/tiflash
- pingcap/tidb-engine-ext
- pingcap/ng-monitoring
- pingcap/tispark
- pingcap/tiunimanager
- pingcap/tiunimanager-ui
- pingcap-inc/tiflash-scripts
- chaos-mesh/chaos-mesh
- chaos-mesh/website
- chaos-mesh/chaosd

### TODO

- [x] ti-community-infra/test-prod
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] ti-community-infra/tichi
  - [x] add `OWNERS` files to the repository.
     - [PR](https://github.com/ti-community-infra/tichi/pull/1169/)
  - [x] change the prow configuration for the repository.
- [x] ti-community-infra/ti-community-bot
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] ti-community-infra/rfcs
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] ti-community-infra/devstats
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] ti-community-infra/devstats-dev-guide
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] tikv/pd
  - [x] https://github.com/tikv/pd/issues/8167
  - [x] #1064
- [x] pingcap/tidb-dashboard
  - [x] add `OWNERS` files to the repository.
  - [ ] change the prow configuration for the repository.
- [x] pingcap/tidb-operator
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tiup
  - [x] add `OWNERS` files to the repository.
  - [ ] change the prow configuration for the repository.
- [x] tikv/tikv
  - [x] https://github.com/tikv/tikv/issues/17004
  - [x] #1063
- [x] pingcap/tidb
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [ ] tikv/community
  - [ ] add `OWNERS` files to the repository.
  - [ ] change the prow configuration for the repository.
- [x] pingcap/community
  - [x] add `OWNERS` files to the repository.
  - [ ] change the prow configuration for the repository.
- [x] pingcap/docs
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/docs-cn
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] ~pingcap/docs-dm~
  - [x] ~add `OWNERS` files to the repository.~
  - [x] ~change the prow configuration for the repository.~
- [x] pingcap/docs-tidb-operator
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tidb-tools
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tiflow
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tidb-binlog
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tiflash
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tidb-engine-ext
  - [x] add `OWNERS` files to the repository.
  - [x] #1066
- [x] pingcap-inc/tiflash-scripts
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/ng-monitoring
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tispark
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tiunimanager
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] pingcap/tiunimanager-ui
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] chaos-mesh/chaos-mesh
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] chaos-mesh/website
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [x] chaos-mesh/chaosd
  - [x] add `OWNERS` files to the repository.
  - [x] change the prow configuration for the repository.
- [ ] tikv/raft-engine
  - [x] #1089
- [ ] tikv/client-go
  - [ ] #1090

**Comment by wuhuizuo** [comment]
How to get the reviewers and approvers for given repo?

**Comment by wuhuizuo** [comment]
should set no_parent_owners to true if github codeowenrs file covered a dir path, like:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2574558/228482734-cc949049-1f99-4bcc-ad49-70ac20077c7e.png">

**Comment by wuhuizuo** [comment]
- [ ] we should delete the config for repo `ti-community-infra/ti-community-bot`, it's archived.

**Comment by wuhuizuo** [comment]
`pingcap/docs-dm` was stopped updating.

**Comment by wuhuizuo** [comment]
The `chaos-mesh/*` repositories will be split to other feedback by maintainers of `chaos-mesh` ORG.

**Comment by wuhuizuo** [comment]
we should archive the `pingcap/docs-dm` repository.
