### ISSUE TITLE
REQUEST: need self approval for `pingcap-qe/tidb-test` repo.

### ISSUE THREAD

**Issue by wuhuizuo** [ti-community-infra/configs#978]
### GitHub Repo Name

`pingcap-qe/tidb-test`

### Which plugins do you want to deploy
You can find all available plugins in [this manual book](https://book.prow.tidb.net/).

e.g. 
- approve

### Requirements
- [x] I have carefully read the instructions for the plugin I want to use.
- [x] I agree to leave the plugin configuration to be maintained by sig-ti-community-infra.

### TODO
- [x] @ti-community-infra/sig-community-infra  Change the requested plugin configuration

**Comment by wuhuizuo** [comment]
//by @bb7133

**Comment by wuhuizuo** [comment]
Currently it is.
